name: seafloor-objects
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pandas
  - geopandas
  - rasterio
  - folium

  # Spatial packages
  - earthpy>=0.9.2

  # Jupyter Environment
  - papermill

  # PEP 8
  # - flake8_nb
