name: seafloor-objects
channels:
  - conda-forge
  - defaults

dependencies:
  - python~=3.8
  # Core scientific python
  - numpy

  # Plotting
  - matplotlib
  - seaborn

  # Spatial packages
  - rasterstats
  - geopy
  - cartopy
  - earthpy
  - folium
  - geojson
  - xarray
  - rioxarray
  - scipy
  - netcdf4  
  - georasters

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook

